config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :courses
  resources :students
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "admins#index"
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong style="color: #0abde3">Name:</strong>
    <%= admin.name %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <%= render admin %>
    <p>
      <%= link_to "Show this admin", admin %>
    </p>
  <% end %>
</div>

<%= link_to "New admin", new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>